import { auth, db, onAuthStateChanged, signOut, doc, getDoc, updateDoc, deleteDoc, serverTimestamp, safeText, categoryLabel, collection, query, where, onSnapshot } from "./firebase.js";

const status=document.querySelector("#dashboardStatus"), panel=document.querySelector("#providerPanel"), editPanel=document.querySelector("#editPanel");
let currentUser=null, provider=null, busyDates=new Set(), stopLeads=null;
const iconMap={decoration:"🎈",photography:"📸",catering:"🍽️",mahal:"🏛️"};

onAuthStateChanged(auth,async user=>{
  if(!user){location.href="login.html";return;} currentUser=user;
  try{const snap=await getDoc(doc(db,"providers",user.uid));if(!snap.exists()){status.textContent="Provider profile not found.";return;}provider=snap.data();busyDates=new Set(Array.isArray(provider.busyDates)?provider.busyDates:[]);render();renderCalendar();loadLeads();}
  catch(e){console.error(e);status.textContent="Could not load your card.";}
});
function render(){status.classList.add("hidden");panel.classList.remove("hidden");document.querySelector("#serviceIcon").textContent=iconMap[provider.category]||"🎉";document.querySelector("#previewBrand").textContent=provider.brandName;document.querySelector("#previewLocation").textContent=provider.location;document.querySelector("#previewCategory").textContent=categoryLabel(provider.category);document.querySelector("#previewPhone").textContent=provider.phone;}
document.querySelector("#logoutBtn").addEventListener("click",async()=>{if(stopLeads)stopLeads();await signOut(auth);location.href="index.html";});
document.querySelector("#editBtn").addEventListener("click",()=>{document.querySelector("#editBrandName").value=provider.brandName||"";document.querySelector("#editName").value=provider.name||"";document.querySelector("#editPhone").value=provider.phone||"";document.querySelector("#editLocation").value=provider.location||"";editPanel.classList.remove("hidden");});
document.querySelector("#cancelEdit").addEventListener("click",()=>editPanel.classList.add("hidden"));
document.querySelector("#editForm").addEventListener("submit",async e=>{e.preventDefault();const msg=document.querySelector("#editMessage");msg.textContent="Updating...";try{await updateDoc(doc(db,"providers",currentUser.uid),{brandName:safeText(document.querySelector("#editBrandName").value),name:safeText(document.querySelector("#editName").value),phone:safeText(document.querySelector("#editPhone").value).replace(/\D/g,""),location:safeText(document.querySelector("#editLocation").value),updatedAt:serverTimestamp()});provider=(await getDoc(doc(db,"providers",currentUser.uid))).data();render();editPanel.classList.add("hidden");msg.textContent="Updated.";}catch(e){console.error(e);msg.textContent="Update failed.";}});
document.querySelector("#deleteBtn").addEventListener("click",async()=>{if(!confirm("Delete your service card? This cannot be undone."))return;try{await deleteDoc(doc(db,"providers",currentUser.uid));await signOut(auth);location.href="index.html";}catch(e){console.error(e);alert("Delete failed.");}});

function loadLeads(){const box=document.querySelector("#providerLeads");const q=query(collection(db,"leads"),where("providerId","==",currentUser.uid));stopLeads=onSnapshot(q,snap=>{const leads=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));if(!leads.length){box.innerHTML='<div class="admin-empty"><strong>No enquiries yet</strong><p>Customer enquiry வந்ததும் இங்கே வரும்.</p></div>';return;}box.innerHTML=leads.map(leadHtml).join("");box.querySelectorAll("[data-confirm-lead]").forEach(b=>b.addEventListener("click",()=>confirmBooking(b.dataset.confirmLead)));box.querySelectorAll("[data-whatsapp-lead]").forEach(b=>b.addEventListener("click",()=>whatsappLead(b.dataset.whatsappLead)));},e=>{console.error(e);box.innerHTML='<div class="admin-empty"><strong>Could not load enquiries</strong><p>Firestore Rules check pannunga.</p></div>';});}
function leadHtml(l){const confirmed=l.status==="confirmed";return `<article class="admin-item"><div class="admin-card-top"><div><span class="eyebrow">Customer Enquiry</span><h3>${esc(l.customerName)}</h3><div class="meta">Lead ID: ${esc(l.id)} · Event Date: ${esc(l.eventDate||"Not selected")}</div><div class="meta">Phone: ${esc(l.customerPhone)}</div></div><span class="admin-active-badge ${confirmed?'active':'inactive'}">${confirmed?'Booking Confirmed':'New Enquiry'}</span></div><div class="admin-info-grid"><div><span>Booking Amount</span><strong>₹${Number(l.bookingAmount||0).toLocaleString('en-IN')}</strong></div><div><span>Commission (3%)</span><strong>₹${Number(l.commissionAmount||0).toLocaleString('en-IN')}</strong></div><div><span>Commission Status</span><strong>${l.commissionPaid?'Paid':'Pending'}</strong></div></div><div class="admin-actions"><button class="primary-btn" data-confirm-lead="${esc(l.id)}">${confirmed?'Update Booking Amount':'Booking Confirmed'}</button><button class="ghost-btn" data-whatsapp-lead="${esc(l.id)}">WhatsApp Customer</button></div></article>`;}
async function confirmBooking(id){const amount=prompt("Booking amount enter pannunga (₹):");if(amount===null)return;const n=Number(String(amount).replace(/[^0-9.]/g,""));if(!Number.isFinite(n)||n<=0){alert("Valid booking amount enter pannunga.");return;}try{await updateDoc(doc(db,"leads",id),{status:"confirmed",bookingAmount:n,commissionRate:3,commissionAmount:Math.round(n*0.03*100)/100,confirmedAt:serverTimestamp(),commissionPaid:false,updatedAt:serverTimestamp()});alert(`Booking confirmed. Event Hub 3% commission: ₹${(n*0.03).toFixed(2)}`);}catch(e){console.error(e);alert("Booking update failed. Check Firestore Rules.");}}
function whatsappLead(id){alert("Customer WhatsApp opening can be added after customer WhatsApp number is configured.");}

const calendarEl=document.querySelector("#availabilityCalendar"),calendarTitle=document.querySelector("#calendarTitle"),prevMonthBtn=document.querySelector("#prevMonth"),nextMonthBtn=document.querySelector("#nextMonth"),saveDatesBtn=document.querySelector("#saveDatesBtn"),calendarMessage=document.querySelector("#calendarMessage");let viewDate=new Date();viewDate.setDate(1);
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function renderCalendar(){if(!calendarEl)return;const y=viewDate.getFullYear(),m=viewDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();calendarTitle.textContent=viewDate.toLocaleString(undefined,{month:"long",year:"numeric"});let html=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=>`<div class="calendar-weekday">${d}</div>`).join("");for(let i=0;i<first.getDay();i++)html+='<div class="calendar-day empty"></div>';for(let day=1;day<=days;day++){const key=dateKey(new Date(y,m,day)),busy=busyDates.has(key);html+=`<button type="button" class="calendar-day ${busy?'busy':'available'}" data-date="${key}" aria-pressed="${busy}"><span>${day}</span><small>${busy?'Work':'Free'}</small></button>`;}calendarEl.innerHTML=html;calendarEl.querySelectorAll("[data-date]").forEach(btn=>btn.addEventListener("click",()=>{const k=btn.dataset.date;if(busyDates.has(k))busyDates.delete(k);else busyDates.add(k);renderCalendar();calendarMessage.textContent="Unsaved changes — click Save Work Dates.";}));}
prevMonthBtn?.addEventListener("click",()=>{viewDate.setMonth(viewDate.getMonth()-1);renderCalendar();});nextMonthBtn?.addEventListener("click",()=>{viewDate.setMonth(viewDate.getMonth()+1);renderCalendar();});saveDatesBtn?.addEventListener("click",async()=>{saveDatesBtn.disabled=true;calendarMessage.textContent="Saving...";try{const sorted=[...busyDates].sort();await updateDoc(doc(db,"providers",currentUser.uid),{busyDates:sorted,updatedAt:serverTimestamp()});provider.busyDates=sorted;calendarMessage.textContent="Work dates saved successfully.";}catch(e){console.error(e);calendarMessage.textContent="Could not save work dates.";}finally{saveDatesBtn.disabled=false;}});
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
